### ISSUE TITLE
No podspec file when installing via NPM

### ISSUE THREAD

**Issue by tavosansal** [capacitor-community/date-picker#1]
Not sure why this is but I tried installing this via NPM and my iOS project is complaining about a missing podspec file. I did double check and sure enough the podspec file does not exists when I install this from NPM even though it is in the repo. 
I also tried installing the repo with the github url `npm install git+https://github.com/stewwan/capacitor-datepick.git#master` and it did not work either...so not sure why that file does not show up on the node_modules.
One theory I have is that the filename does not match here `https://github.com/stewwan/capacitor-datepick/blob/master/package.json#L31`

**Comment by danielprrazevedo** [comment]
> Not sure why this is but I tried installing this via NPM and my iOS project is complaining about a missing podspec file. I did double check and sure enough the podspec file does not exists when I install this from NPM even though it is in the repo.
> I also tried installing the repo with the github url `npm install git+https://github.com/stewwan/capacitor-datepick.git#master` and it did not work either...so not sure why that file does not show up on the node_modules.
> One theory I have is that the filename does not match here `https://github.com/stewwan/capacitor-datepick/blob/master/package.json#L31`

We are going through a change in the community and I will try to keep the plugin. xD
Could you check if after the last update the problem persists?
So we can close the issue
