### ISSUE TITLE
Date returned diferent date selected

### ISSUE THREAD

**Issue by danielprrazevedo** [capacitor-community/date-picker#12]
**Describe the bug**
When I using the default format, the date value returned comes with the wrong hours and minutes

**To Reproduce**
1. open the plugin without the format in options
2. select date and time
3. compare returned value and selected value

**Expected behavior**
must return the same selected date

**Smartphone (please complete the following information):**
 - Device: Emulators
 - Browser stock browser

**Comment by roxteddy** [comment]
Are you sure it is not a timezone issue ?
what are the selected date & time and the output value ?
