### ISSUE TITLE
Locale ignored under Material Design

### ISSUE THREAD

**Issue by carolineoliva** [capacitor-community/date-picker#15]
Under Material Design themes, locale set in DatePicker.present is ignored. Under Material Design, months and days names are localized according to system locale.

It's easy to reproduce. Simply set a different locale when creating the DatePicker. E.g.:
Supposing my OS locale is pt-BR, if I set locale as 'en_US' (or 'en')
    DatePicker.present({
      mode: 'date',
      locale: 'en_US',
      date: currentDate,
      format: 'yyyy-MM-dd',
      theme: selectedTheme
    }).then((date)....
I'll get Janeiro, Fevereiro. Março.... instead of January, February, March...

I was able to fix the issue by changing DatePickerPlugin.java.
I added the following lines after 'Locale.setDefault(locale);' (line 103):
Configuration config = new Configuration();
config.locale = locale;
getContext().getResources().updateConfiguration(config, getContext().getResources().getDisplayMetrics());

**Comment by danielprrazevedo** [comment]
Hey @carolineoliva, thanks for already bringing us the solution. If you managed to solve the problem, open a PR that we accept, no problem :)
That way we will keep your contribution recorded in git-history
