### ISSUE TITLE
Min and max not working

### ISSUE THREAD

**Issue by gentlemanjohn** [capacitor-community/date-picker#19]
**Describe the bug**
Min and max are not recognized.  Using static min and max dates, the picker allows the selection of dates before the min and does not allow the selection of dates before the max.  When the min and max are set dynamically, the picker breaks and only allows the selection of a single, arbitrary date in the past.  Oddly when that date is selected, a year is added to it.

**To Reproduce**

In my example I have two ion-item buttons with a click handler that launches the picker.  One sets the arrival date, the other sets the departure date.  In the dynamic dates example (what I'm really aiming for), after the arrival date is set, the departure min is set to one day after the arrival date and the departure max is set to 30 days after the arrival date.

**Template:**
`<ion-item button (click)="datePicker('arrival')">Arrival</ion-item>`
`<ion-item button (click)="datePicker('departure')">Departure</ion-item>`

**Angular Component:**

with static dates:
```
datePicker(point) {
  DatePicker
      .present({
        mode: "date",
        date: this.stopForm.get(point).value,
        format: 'YYYY-MM-dd',
        min: '2020-01-01',
        max: '2021-05-21'
      })
      .then((date) => {
        alert(date.value);
        this.stopForm.get(point).setValue(date.value);
        this.stopForm.get(point).markAsDirty();
      });
}
```
with dynamic dates:
```
datePicker(point) {
  DatePicker
      .present({
        mode: "date",
        date: this.stopForm.get(point).value,
        format: 'YYYY-MM-dd',
        min: min,
        max: max
      })
      .then((date) => {
        alert(date.value);
        this.stopForm.get(point).setValue(date.value);
        this.stopForm.get(point).markAsDirty();
      });
}
```

I use the date picker to select an arrival date of October 4, 2020.  My code seems to be setting the appropriate mins and maxes. 
 However, when I go to select the departure date, the date picker defaults to December 29, 2019 (see screenshot) and I am not able to select any other date.    When I confirm, the date value is actually December 29, 2020 (see screenshot).

**Expected behavior**
I expect the date picker to:
1. Allow all dates within the allowed range to be selectable
2. Make it impossible to select a date outside of the allowed range
3. Default to the min value if today's date is not within the allowed range

**Screenshots**
![1](https://user-images.githubusercontent.com/3412604/95276743-e7fbe780-0800-11eb-8c95-575c0233fc86.jpg)
![2](https://user-images.githubusercontent.com/3412604/95276747-ea5e4180-0800-11eb-815a-214d28bbdbf0.jpg)
![3](https://user-images.githubusercontent.com/3412604/95276751-ec280500-0800-11eb-8fd9-7f57ca2a3feb.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 11
 - Browser: N/A
 - Version: 0.2.1

**Comment by danielprrazevedo** [comment]
@gentlemanjohn First of all, sorry about that, we need to improve the documentation a little bit in this regard.
Your date format is not correct, try to follow [this](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) pattern to set your calendar format
`format: 'yyyy-MM-dd',`

**Comment by gentlemanjohn** [comment]
Ah OK, `format: yyyy-MM-dd` fixed it for me.  FYI I was using the latest version of date-picker, 0.2.1. Typo on my part. 

Just a heads up for anyone else that is using moment.js (2.29.0), the formatting is a little different: `YYYY-MM-DD` matches date-picker's `yyyy-MM-dd`
