### ISSUE TITLE
iOS Wrong time format on preview if is24h is true

### ISSUE THREAD

**Issue by Jannnnnn** [capacitor-community/date-picker#21]
**Describe the bug**
if `is24h` is set true the and the `mode` is time, the title should not show AM/PM.

**To Reproduce**
Open the DatePicker with these settings on iOS

```ts
{
    mode: 'time',
    is24h: true,
    locale: 'de_DE',
    doneText: 'Ok',
    cancelText: 'Zurück',
}
```

**Expected behavior**
The time should show 13:17 not 13:17 PM

**Screenshots**
![Bildschirmfoto 2020-10-08 um 13 36 37](https://user-images.githubusercontent.com/21027386/95454013-24982200-096c-11eb-814f-5ec18ec74655.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.5
 - Browser stock capacitor

**Comment by roxteddy** [comment]
`is24h` forces 24h display despite your phone setup (and add `hours`, `min.` in wheel)

I see 3 problems here :

- AM/PM is always added in title (even with `is24h` false)
- The title is always in 24h format for me - even if I provide a date with `hh:mm a` format
`const format = "hh:mm a";
        const date = moment(this.publishingDate).format(format);`
( And even then, the title format should depend on phone configuration to match wheel display)
- `hours` and `min.` annotations in wheel should not depend on "is24h" - It makes sense only if you are defining a length

**Comment by roxteddy** [comment]
Hi @danielprrazevedo

Actually, AM/PM is really ALWAYS added. Even if I input "2:55 pm"

![0](https://user-images.githubusercontent.com/6069870/97891089-a3e00200-1d2e-11eb-885b-4c95a04f251a.jpg)
