### ISSUE TITLE
Capacitor 3 Support

### ISSUE THREAD

**Issue by thomasvidas** [capacitor-community/date-picker#30]
Capacitor 3 is currently in alpha (with a beta quickly approaching!). It would be great if this plugin released a Capacitor 3 compatible version around the same time as the full release.

Happy to help out if I can 😄

**Comment by danielprrazevedo** [comment]
Hello @thomasvidas!
I just did a beta publication of the plugin, I would love it if you could test it and give me feedback

npm install @ capacitor-community/date-picker@beta
beta [doc](https://github.com/capacitor-community/date-picker/tree/feat/3.0.0-release)

Please note that we have some changes to the plugin and the way it is called

**Comment by CedNet** [comment]
I'd just like to bump this like a prick but also say that your beta version does work with Capacitor 3 on a project I just upgraded :-)

Any chance for a release outside of beta soon?

**Comment by CedNet** [comment]
Well, actually. My IDE was happy, but ionic build was not.

Gives the following error using the example code. How can this be adjusted to work with capacitor 3 as it does work with capacitor 2?

(im using @beta)

 **import {DatePickerPlugin, DatePickerPluginInterface} from '@capacitor-community/date-picker';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/search/search.page.ts:11:47 - error TS2693: 'DatePickerPlugin' only refers to a type, but is being used as a value here.

11 const DatePicker: DatePickerPluginInterface = DatePickerPlugin;
                                                 ~~~~~~~~~~~~~~~~**

**Comment by rpascal** [comment]
Any word if we can expect Capacitor 3 support in the near feature?

**Comment by danielprrazevedo** [comment]
Yes we can.
I'll try to make another release this week, I confess that I'm a little out of time to finish everything, but there is already a beta version for capacitor 3, but some features on android are still incomplete

**Comment by amanngoel** [comment]
Hey @danielprrazevedo , when can we expect a stable release for Capacitor 3

**Comment by amitkrgautm** [comment]
@danielprrazevedo Any update about stable release.

**Comment by sburnicki** [comment]
Any update on this? 😊 This is the last plugin that keeps me from updating to capacitor3 in my project.

**Comment by NLueg** [comment]
I use the version in my productive app for like 3 weeks on iOS and Android and don't experience any issues.
In my opinion, the beta release can be marked as stable.

**Comment by aliantjamaica** [comment]
@danielprrazevedo any update on the capacitor v3 datepicker fix??

**Comment by aliantjamaica** [comment]
> Yes we can.
> I'll try to make another release this week, I confess that I'm a little out of time to finish everything, but there is already a beta version for capacitor 3, but some features on android are still incomplete

@danielprrazevedo any update?

**Comment by jjacobs33589** [comment]
I've updated to capacitor 3 and this is the only plugin having problems because it doesn't support capacitor 3

**Comment by NLueg** [comment]
@jjacobs33589 you can use the beta-version for your Cap 3 app.
You can install it with:

```sh
npm install @ capacitor-community/date-picker@beta
``` 

In my opinion, this release can be marked as stable as I use the code in production for like 2 months.

**Comment by nirajhinge** [comment]
Just noticed what looks like an error with the beta build if we try to install it on `capacitor 3.2.3` with the following dependency issue:
```shell
➜ npm install @capacitor-community/date-picker@beta
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@0.0.1
npm ERR! Found: @capacitor/core@3.2.3
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"3.2.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"3.0.0-beta.1" from @capacitor-community/date-picker@0.3.0
npm ERR! node_modules/@capacitor-community/date-picker
npm ERR!   @capacitor-community/date-picker@"0.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
This seems to be an issue because the dependencies on the project is locked on this capacitor version `3.0.0-beta.1`. Works if we use the --force flag for now.

**Comment by bram96** [comment]
Is there a plan for releasing a stable version for Capacitor 3?

**Comment by elvisgraho** [comment]
Ionic Framework v6 ditched their old `ion-datetime` and this plugin seems like an alternative to Ionic's "depracted" datepicker

**Comment by pioneersingh321** [comment]
Error: Uncaught (in promise): Error: Method not implemented.
Error: Method not implemented. at DatePickerWeb.present

**Comment by Pynka** [comment]
Maybe this helps you: https://github.com/capacitor-community/date-picker/issues/63#issuecomment-1217887124
