### ISSUE TITLE
Timezone parametr

### ISSUE THREAD

**Issue by pankominek** [capacitor-community/date-picker#37]
What are the values of the timezone parameter? 
Unfortunately, when I enter the timezone: 'Europe / Warsaw' or 'UTC + 2' I do not see any effect.

```
  const selectDateTime = async () => {
      const selectedDateTime = await Plugins.DatePickerPlugin.present({
        mode: props.mode,     
        theme: 'light',
        is24h: true,
        timezone: 'Europe/Warsaw',
        min: new Date().toISOString()
      });
```

**Comment by danielprrazevedo** [comment]
@pankominek You must use the short form of timezone as `GMT+3` or something, currently, the plugin does not support location definitions. In an update I will put the plugin to work by default with the device's timezone. I currently have little time to improve the plugin settings

**Comment by pankominek** [comment]
Great, thanks for the valuable information.
