### ISSUE TITLE
iOS 14: calendar view for date selection

### ISSUE THREAD

**Issue by dimitrijuchtmans** [capacitor-community/date-picker#38]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
When using mode: 'date', I would like to be able to have a calendar view instead of the wheel, and a fallback to wheel on < iOS 14

**Describe alternatives you've considered**
other libraries, like duet-datepicker

**Additional context**
https://www.swiftpal.io/articles/new-uidatepicker-in-ios-14

**Comment by dimitrijuchtmans** [comment]
Basicly this like should be editable by some input config:
self.picker?.preferredDatePickerStyle = UIDatePickerStyle.**wheels**

**Comment by danielprrazevedo** [comment]
I am working on this for a new version of the datepicker, this is available in v0.3 which will be used in conjunction with the capacitor v3

**Comment by dimitrijuchtmans** [comment]
Cool! Got any idea on release date?

**Comment by danielprrazevedo** [comment]
I'm currently a little busy, so I think that someday in May I should release this realease. 
But if you install it with `npm i @capacitor-community/date-picker@0.3.0`, you can test it.

**Comment by dimitrijuchtmans** [comment]
I guess the 0.3.0 version only works with capacitor 3+ as well? since the datepicker is telling me 
"export 'registerPlugin' was not found in '@capacitor/core' :)

**Comment by dimitrijuchtmans** [comment]
Hi, just to come back. After following the capacitor update to 3.0 guide and inserting the community datepicker beta version, it seems to work on my iphone.
![image](https://user-images.githubusercontent.com/6793282/115232512-1135f280-a117-11eb-9565-e4070115d6a2.png)

One little bug that may or not may be discovered yet: i pass locale NL: this causes the month to show dutch indeed, but the days remain in english whatever locale i pass.

**Comment by Ong26** [comment]
> @danielprrazevedo, Updated my capacitor and inserted beta version of datepicker. it works. ![image](https://user-images.githubusercontent.com/6793282/115232512-1135f280-a117-11eb-9565-e4070115d6a2.png)
> 
> One little bug: passing a locale does update the month value, but not the day values.

Can I know which version of @capacitor-community/date-picker that you are using? Because I am facing issue in iOS device by using v0.2.3
