### ISSUE TITLE
DatePicker positioning issue on iOS with keyboard visible

### ISSUE THREAD

**Issue by davpirelli** [capacitor-community/date-picker#48]
**Describe the bug**
On iOS, when the keyboard is visible and a click is made in a field with event DatePicker.present result in datepicker ui goes in the middle of the screen (see attached gif)

**Config**
`Ionic:`
`   Ionic CLI                                      : 6.16.3`
`   Ionic Framework                         : @ionic/angular 5.6.11`
`   @angular-devkit/build-angular : 0.1102.9`
`   @angular-devkit/schematics    : 11.2.9`
`   @angular/cli                                : 11.2.9`
`   @ionic/angular-toolkit                : 3.1.1`

`Capacitor:`
`   Capacitor CLI           : 2.4.7`
`   @capacitor/android : 2.4.7`
`   @capacitor/core      : 2.4.7`
`   @capacitor/ios         : 2.4.7`

`Utility:`
`   cordova-res                                       : 0.15.3`
`   native-run (update available: 1.4.0) : 1.3.0`

`System:`
`   NodeJS : v14.15.4 (/usr/local/bin/node)`
`   npm       : 6.14.10`
`   OS         : macOS Big Sur`

**Expected behavior**
The date-picker ui shoud be fixed at the bottom.

**Screenshots**
![ezgif-2-013632a0a183](https://user-images.githubusercontent.com/6840116/125408679-6f434080-e3bb-11eb-8d7e-a2b7e7b63b00.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.5

**Comment by Saqib92** [comment]
Can use `Keyboard.hide()` before `DatePicker.present` to hide keyboard.

**Comment by davpirelli** [comment]
Thanks, that solved the issue!
