### ISSUE TITLE
Date Picker Date and Time input simultaneously

### ISSUE THREAD

**Issue by joplaete** [capacitor-community/date-picker#5]
Hey is it possible to get this date-picker to show date and time simultaneously as follows:
![Screenshot 2020-08-02 at 14 15 37](https://user-images.githubusercontent.com/609778/89123921-f230fb00-d4ca-11ea-9b09-4edb367ca84a.png)
I'm currently getting date and time sequentially presented. Tried a few formats but mostly getting the app crashing when I thinker with those.
& on a related note: is it possible to hide the 'date preview' at the top?
Thanks!

**Comment by danielprrazevedo** [comment]
@joplaete When I started the development of the plugin, I tried my best to keep the consistency between the displays for android and ios, do you know any way to apply this display for android?
Another thing that we can pay attention to would be where would we put this exhibition, if we treated it as a theme or mode exhibition? I, in particular, would prefer to treat this as a theme, but I would like to know what you think of it.

**Comment by joplaete** [comment]
Thanks for getting back to this @danielprrazevedo.
Not that familiar with android so not sure what the android flavour of this would look like sorry.
In terms of what would drive it.. you could go for the theme route although to me this feels more functionality over styling so perhaps mode is a better way to define it? e.g. 'dateThenTime' or something along those lines?  Up to you though, don't have a strong preference.

**Comment by danielprrazevedo** [comment]
I was thinking of some ways to perform this feat, I think that while I can add one more option to the `PickerOptions`, something like `mergedDateAndTime: boolean` where it will have something specific for ios, as well as the color customizations of the picker, which you think?

**Comment by joplaete** [comment]
Sounds good to me!
