### ISSUE TITLE
Value of optional type 'CAPBridgeProtocol?' must be unwrapped to refer to member 'config

### ISSUE THREAD

**Issue by Slayess** [capacitor-community/date-picker#53]
**Describe the bug**
Error occured during the XCode compilation 

**Expected behavior**
Error displayed :  Swift compiler error Value of optional type 'CAPBridgeProtocol?' must be unwrapped to refer to member 'config' of wrapped base type 'CAPBridgeProtocol'

**Screenshots**
![11](https://user-images.githubusercontent.com/52039612/148804548-2681bc4d-f5db-45f4-b27a-ebd9a37ec2c5.jpg)

**Desktop (please complete the following information):**
 - macOS 12.1
 - XCode 13.1

Thanks in advance for your help

**Comment by Ong26** [comment]
I think you are using date picker of version 0.2.3 with capacitor v3. Will works fine after changing DatePicker to the beta version (0.3.0)

**Comment by sagargowda** [comment]
@Ong26 i am using @capacitor/core 3.4.3 and as you suggested tried changing DatePicker to the beta version (0.3.0) but not able to install because its below error please check.
<img width="554" alt="date-picker-error" src="https://user-images.githubusercontent.com/14043167/164188251-f029e1fb-acfa-4811-8d2a-92d108edb66c.png">

**Comment by nijakobius** [comment]
Getting similar errors (on macOS Ventura 13.0, Xcode 14.1, @capacitor-community/date-picker@0.2.3):

<img width="1783" alt="Screenshot 2022-11-21 at 23 51 45" src="https://user-images.githubusercontent.com/37240226/203173969-3c4a7b66-2288-4cf7-a48f-30a919607d7b.png">

...and also cannot install 0.3.0:

<img width="659" alt="Screenshot 2022-11-21 at 23 54 17" src="https://user-images.githubusercontent.com/37240226/203174463-28bbb879-b1c3-424b-a501-32bff5d020c8.png">

**Comment by jcesarmobile** [comment]
this is fixed in version 3.0.0
