### ISSUE TITLE
Release Date of Date-Picker 0.3.0

### ISSUE THREAD

**Issue by ivo-vutov-ms** [capacitor-community/date-picker#59]
Hello all,

we are using currently the date-picker plugin version 0.2.3 with Capacitor 2. We were wondering if this project is still being updated at some point in the future or if it has been abandoned. We would love to use 0.3.0 for our upcoming upgrade to Capacitor 3 but we cannot proceed with the current version for productive scenarios. 

# Thank you for your reply in advance!

**Comment by modvd** [comment]
I just switched to regular HTML date inputs. They are less flexible but at least they work.

**Comment by NLueg** [comment]
@modvd how did you manage it to make it work in iOS?

**Comment by NLueg** [comment]
However I just created a fork of this plugin and created a version that supports even Capacitor 4: https://www.npmjs.com/package/@pantrist/capacitor-date-picker

**Comment by jcesarmobile** [comment]
I've released version 3.0.0 with Capacitor 3 support, will try to release 4.0.0 with Capacitor 4 support soon.
