### ISSUE TITLE
Time minutes preview broken on iOS?

### ISSUE THREAD

**Issue by joplaete** [capacitor-community/date-picker#6]
I'm feeding following date into the options
`date: "2020-08-02T16:00:00.000Z"`
The pickers seem to be initialising correctly, except the preview time seems to have an offset in minutes and minutes are not updating when I change them in the time picker (date and hours are updating correctly as I change them).
![IMG_2916](https://user-images.githubusercontent.com/609778/89124308-e2ff7c80-d4cd-11ea-8401-de928ac9f3ea.jpg)
![IMG_2917](https://user-images.githubusercontent.com/609778/89124312-e6930380-d4cd-11ea-8dba-c0ff656a2735.jpg)
The date that gets returned also reflects the correct date and time (including minutes) chosen by the pickers.
Am I doing something wrong or is something broken on the iOs end?

```
iOS 13.5.1
"@capacitor-community/date-picker": "^0.1.0",
"@capacitor/core": "^2.4.0",
"@capacitor/ios": "^2.4.0",
```
Thanks

**Comment by danielprrazevedo** [comment]
@joplaete I believe that you are not doing anything wrong, this may be a bug in the plugin.
When I create the datepicker, on iOS, I reused only the time, I will try to upload a fix later this weekend
