### ISSUE TITLE
Android initialising AM for PM Time

### ISSUE THREAD

**Issue by joplaete** [capacitor-community/date-picker#7]
When initialising following date on android 
`
mode: 'dateAndTime',
date: '2020-08-02T16:00:00.000Z', 
is24h: true
`
Date is correct but it seems to transform the PM time (16) to AM. It does so with is24h set to true and false.
<img width="389" alt="Screenshot 2020-08-02 at 15 16 10" src="https://user-images.githubusercontent.com/609778/89125297-61135180-d4d5-11ea-9df5-a7a4e27a3475.png">
<img width="394" alt="Screenshot 2020-08-02 at 15 16 30" src="https://user-images.githubusercontent.com/609778/89125299-67093280-d4d5-11ea-8009-7417fb10dda9.png">

Getting to that date string by calling .toISOString() on a date as seen in the example. iOS seems to be handling this correctly (except the preview minutes issue flagged in https://github.com/capacitor-community/date-picker/issues/6)
Is that a wrong way of passing on the date or is something broken?

`
Android 9.0
"@capacitor-community/date-picker": "^0.1.0",
"@capacitor/core": "^2.4.0",
"@capacitor/android": "^2.4.0",`

Thanks

**Comment by danielprrazevedo** [comment]
@joplaete Probably something is broken.
Is this a problem for entry only or does it also happen on the return date?
I will try to upload a fix of this next to #6

**Comment by joplaete** [comment]
It returns the transformed date for me, so if it initialises a 4pm for a 4am it'll return 4am.
