### ISSUE TITLE
Add backdrop on iOS when date picker is open

### ISSUE THREAD

**Issue by yacut** [capacitor-community/date-picker#8]
it would be a nice to add a background for inactive part so that the user can see where the date picker ends:

<img width="269" alt="React_Native_DatePicker_Modal_Component_for_iOS_Android" src="https://user-images.githubusercontent.com/4711633/89164949-1565b400-d578-11ea-84f6-4b5709a4fe4b.png">

**Comment by danielprrazevedo** [comment]
@yacut I appreciate the proposal, but I confess that I don't have that much knowledge with Swift.
At the moment I have some bugs reported, as soon as I resolve them, I will try to fulfill your request, if you have any idea how to proceed with this, I am grateful for the help.
